### ISSUE TITLE
rsfmri errors

### ISSUE THREAD

**Issue by elijahrockers** [merky/nacc_rsfmri#1]
When running the `rsfmri_preproc` script I get some errors, although the script does seem to complete anyway.

`Cannot open volume /space/nnac/alzheimer_center/subjects/rs-fmri/ELIJAH_buckner_nnac_preproc_test/081028_BC77WB/restproc/rest01_reorient_skip_tc_mc_brain_atl_affine for reading!`

Do you recall what are supposed to be the outputs, when the smoke clears? It also shows errors when referencing bpss_resid files that it supposedly is supposed to create. Some of Belen's proccessing attempts (before I was hired) are missing these files as well, but there are some others that do have them (and were passed two functional (as opposed to anatomical) files instead)

I tried recreating the processing of one that had two functional scans, but the bpss_resid files did not get created.

Was there perhaps an extra processing step after you run rsfmri_preproc, or maybe the script is broken somehow, now?

**Comment by elijahrockers** [comment]
Tried this making sure SPM8 was being used (instead of SPM12) still no dice.

**Comment by qufunk** [comment]
This is actually a simple fix. Line 281 needs to be changed to 

`output=${fpath}_mean_brain_atl_`
